# Generated by Django 4.0.4 on 2022-05-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='about_content',
            field=models.TextField(default=''),
        ),
    ]
